config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  get "form", to: "pages#form", as: :form
  get "answer", to: "pages#answer", as: :answer
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def form

  end

  def answer
    @answer = ""
    if params[:question] == " I am going to work"
      @answer = "Great!"
    elsif params[:question].last == "?"
      @answer = "Silly question, get dressed and go to work!"
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>

  <body>
    <div class="container mx-16 my-8 bg-warning-subtle">
      <h1 style="font">Stupid Coaching</h1>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/answer.html.erb
<div class="question border-start border-5 px-3 py-1">
  <p><%= params[:question] %></p>
  <p>- Your question</p>
</div>

<div class="answer border-start border-5 px-3 py-1">
  <p><%= @answer %></p>
  <p class="coach_answer">- Your coach</p>
</div>

<div class="back-to-new-question">
  <%= link_to "Ask a new question", form_path%>
</div>

app/views/pages/form.html.erb
<form action="answer" method="get">
  <div class="mb-3">
    <label for="question" class="form-label">Ask the coach anything!</label>
    <input type="text" class="form-control" id="question" name="question">
  </div>
  <button type="submit" class="btn btn-primary">Ask</button>
</form>